// Do not edit. This file is machine generated by the Resource DLL Wizard.

library MOney;

{ITE} {DFMFileType} {TelaConsultaBcd.dfm}
{ITE} {DFMFileType} {telaentrada.dfm}
{ITE} {DFMFileType} {UnitCadastraCaixa.dfm}
{ITE} {DFMFileType} {UnitCadastraLinha.dfm}
{ITE} {DFMFileType} {UnitCadastraParam.dfm}
{ITE} {DFMFileType} {UnitCadastraTipoLinha.dfm}
{ITE} {DFMFileType} {UnitCadastroVeiculos.dfm}
{ITE} {DFMFileType} {UnitConsultaveiculos.dfm}
{ITE} {DFMFileType} {UnitDadosMov.dfm}
{ITE} {DFMFileType} {UnitIniciaSistema.dfm}
{ITE} {DFMFileType} {UnitLancamento.dfm}
{ITE} {DFMFileType} {UnitRelatorio.dfm}
{ITE} {DFMFileType} {UnitRelatorioCentral.dfm}
{ITE} {DFMFileType} {UnPai.dfm}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {RCFileType} {MOney_DRC.rc}

{$R 'TelaConsultaBcd.dfm' FormConsultaMovimento:TForm}
{$R 'telaentrada.dfm' formEntrada:TForm}
{$R 'UnitCadastraCaixa.dfm' FormCadastraCaixa:TForm}
{$R 'UnitCadastraLinha.dfm' FormCadastraLinha:TForm}
{$R 'UnitCadastraParam.dfm' FormCadastraParam:TForm}
{$R 'UnitCadastraTipoLinha.dfm' FormCadastraTipoLinha:TForm}
{$R 'UnitCadastroVeiculos.dfm' FormCadastroVeiculos:TForm}
{$R 'UnitConsultaveiculos.dfm' FormConsultaVeiculos:TForm}
{$R 'UnitDadosMov.dfm' FormDadosMov:TForm}
{$R 'UnitIniciaSistema.dfm' FormIniciaSistema:TForm}
{$R 'UnitLancamento.dfm' FormLancamento:TForm}
{$R 'UnitRelatorio.dfm' Relatorio:TForm}
{$R 'UnitRelatorioCentral.dfm' FormRelatorioCentral:TForm}
{$R 'UnPai.dfm' Pai:TDataModule}
{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'MOney_DRC.res' 'MOney_DRC.rc'}

{$E PTB}

begin
end.